# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
image:
  repository: ghcr.io/23technologies/gardener-extension-shoot-kubecost
  tag: latest
  pullPolicy: IfNotPresent

serviceName: shoot-kubecost
replicaCount: 1
ignoreResources: false

controllers:
  lifecycle:
    concurrentSyncs: 5
  healthcheck:
    concurrentSyncs: 5
  ignoreOperationAnnotation: false

gardener:
  version: ""
