name: go:test

on:
  pull_request:
    paths-ignore: 'docs/**'
  push:
    branches: ['main']
    paths-ignore: 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ "1.23" ]

    steps:
    - name: Checkout commit
      uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Execute tests
      run: make test-cov
